// iconos-fa.js — Catálogo curado de íconos Font Awesome 6 (free) para la
// sección Iconos del dashboard (iconos-pie).
//
// Cada entrada: { clase, etiqueta }. La etiqueta (y la clase) se usan para
// el buscador del selector. Solo se listan nombres válidos de FA 6.5.1 free
// (fa-solid y fa-brands), cubriendo los usos típicos de una tienda:
// pagos, envíos, garantías, soporte, contacto y redes.

export const ICONOS_FONT_AWESOME = [
    // ---- Pagos y dinero ----
    { clase: 'fa-solid fa-credit-card', etiqueta: 'Tarjeta de crédito' },
    { clase: 'fa-solid fa-bank', etiqueta: 'Banco' },
    { clase: 'fa-solid fa-wallet', etiqueta: 'Billetera' },
    { clase: 'fa-solid fa-money-bill-wave', etiqueta: 'Dinero / billetes' },
    { clase: 'fa-solid fa-money-bill-transfer', etiqueta: 'Transferencia' },
    { clase: 'fa-solid fa-money-bill-1', etiqueta: 'Peso / moneda' },
    { clase: 'fa-solid fa-cash-register', etiqueta: 'Caja registradora' },
    { clase: 'fa-solid fa-receipt', etiqueta: 'Ticket / recibo' },
    { clase: 'fa-solid fa-barcode', etiqueta: 'Código de barras' },
    { clase: 'fa-solid fa-qrcode', etiqueta: 'Código QR' },
    { clase: 'fa-solid fa-tag', etiqueta: 'Etiqueta' },
    { clase: 'fa-solid fa-tags', etiqueta: 'Etiquetas / precios' },
    { clase: 'fa-solid fa-percent', etiqueta: 'Descuento / porcentaje' },
    { clase: 'fa-solid fa-hand-holding-dollar', etiqueta: 'Pago en mano' },
    { clase: 'fa-solid fa-handshake', etiqueta: 'Acuerdo / confianza' },
    { clase: 'fa-solid fa-piggy-bank', etiqueta: 'Ahorro' },
    { clase: 'fa-solid fa-coins', etiqueta: 'Monedas' },
    { clase: 'fa-solid fa-sack-dollar', etiqueta: 'Bolsas de dinero' },

    // ---- Marcas de pago (fa-brands) ----
    { clase: 'fa-brands fa-cc-visa', etiqueta: 'Visa' },
    { clase: 'fa-brands fa-cc-mastercard', etiqueta: 'Mastercard' },
    { clase: 'fa-brands fa-cc-amex', etiqueta: 'American Express' },
    { clase: 'fa-brands fa-paypal', etiqueta: 'PayPal' },
    { clase: 'fa-brands fa-cc-paypal', etiqueta: 'PayPal (tarjeta)' },
    { clase: 'fa-brands fa-google-pay', etiqueta: 'Google Pay' },
    { clase: 'fa-brands fa-apple-pay', etiqueta: 'Apple Pay' },
    { clase: 'fa-brands fa-btc', etiqueta: 'Bitcoin' },

    // ---- Envíos y logística ----
    { clase: 'fa-solid fa-truck', etiqueta: 'Camión / envío' },
    { clase: 'fa-solid fa-truck-fast', etiqueta: 'Envío rápido' },
    { clase: 'fa-solid fa-truck-ramp-box', etiqueta: 'Descarga / carga' },
    { clase: 'fa-solid fa-truck-moving', etiqueta: 'Mudanza' },
    { clase: 'fa-solid fa-truck-arrow-right', etiqueta: 'Envío en camino' },
    { clase: 'fa-solid fa-van-shuttle', etiqueta: 'Furgoneta' },
    { clase: 'fa-solid fa-box', etiqueta: 'Caja / paquete' },
    { clase: 'fa-solid fa-boxes-stacked', etiqueta: 'Paquetes apilados' },
    { clase: 'fa-solid fa-box-open', etiqueta: 'Caja abierta' },
    { clase: 'fa-solid fa-box-archive', etiqueta: 'Paquete archivado' },
    { clase: 'fa-solid fa-cube', etiqueta: 'Cubo' },
    { clase: 'fa-solid fa-warehouse', etiqueta: 'Depósito' },
    { clase: 'fa-solid fa-plane', etiqueta: 'Avión' },
    { clase: 'fa-solid fa-plane-departure', etiqueta: 'Avión despegue' },
    { clase: 'fa-solid fa-plane-arrival', etiqueta: 'Avión llegada' },
    { clase: 'fa-solid fa-ship', etiqueta: 'Barco' },
    { clase: 'fa-solid fa-car', etiqueta: 'Auto' },
    { clase: 'fa-solid fa-car-side', etiqueta: 'Auto de lado' },
    { clase: 'fa-solid fa-motorcycle', etiqueta: 'Moto' },
    { clase: 'fa-solid fa-bicycle', etiqueta: 'Bicicleta' },
    { clase: 'fa-solid fa-bus', etiqueta: 'Colectivo' },
    { clase: 'fa-solid fa-train-subway', etiqueta: 'Subte' },
    { clase: 'fa-solid fa-suitcase', etiqueta: 'Valija' },
    { clase: 'fa-solid fa-location-dot', etiqueta: 'Ubicación' },
    { clase: 'fa-solid fa-map-pin', etiqueta: 'Pin de mapa' },
    { clase: 'fa-solid fa-map', etiqueta: 'Mapa' },
    { clase: 'fa-solid fa-route', etiqueta: 'Ruta / recorrido' },
    { clase: 'fa-solid fa-compass', etiqueta: 'Brújula' },
    { clase: 'fa-solid fa-globe', etiqueta: 'Globo / todo el país' },

    // ---- Garantías y seguridad ----
    { clase: 'fa-solid fa-shield', etiqueta: 'Escudo' },
    { clase: 'fa-solid fa-shield-halved', etiqueta: 'Escudo de seguridad' },
    { clase: 'fa-solid fa-shield-heart', etiqueta: 'Protección' },
    { clase: 'fa-solid fa-shield-virus', etiqueta: 'Escudo con protección' },
    { clase: 'fa-solid fa-lock', etiqueta: 'Candado / seguro' },
    { clase: 'fa-solid fa-lock-open', etiqueta: 'Candado abierto' },
    { clase: 'fa-solid fa-key', etiqueta: 'Llave' },
    { clase: 'fa-solid fa-fingerprint', etiqueta: 'Huella digital' },
    { clase: 'fa-solid fa-user-shield', etiqueta: 'Usuario protegido' },
    { clase: 'fa-solid fa-user-check', etiqueta: 'Usuario verificado' },
    { clase: 'fa-solid fa-user-lock', etiqueta: 'Cuenta con candado' },
    { clase: 'fa-solid fa-check-to-slot', etiqueta: 'Verificación aprobada' },
    { clase: 'fa-solid fa-circle-check', etiqueta: 'Círculo aprobado' },
    { clase: 'fa-solid fa-square-check', etiqueta: 'Casilla aprobada' },
    { clase: 'fa-solid fa-check', etiqueta: 'Check' },
    { clase: 'fa-solid fa-check-double', etiqueta: 'Doble check' },
    { clase: 'fa-solid fa-certificate', etiqueta: 'Certificado' },
    { clase: 'fa-solid fa-award', etiqueta: 'Premio / garantía' },
    { clase: 'fa-solid fa-medal', etiqueta: 'Medalla' },
    { clase: 'fa-solid fa-trophy', etiqueta: 'Trofeo' },
    { clase: 'fa-solid fa-crown', etiqueta: 'Corona / categoría' },
    { clase: 'fa-solid fa-gem', etiqueta: 'Gema / calidad' },
    { clase: 'fa-solid fa-star', etiqueta: 'Estrella' },
    { clase: 'fa-solid fa-heart', etiqueta: 'Corazón' },
    { clase: 'fa-solid fa-thumbs-up', etiqueta: 'Me gusta' },

    // ---- Garantía y devoluciones ----
    { clase: 'fa-solid fa-rotate-left', etiqueta: 'Devolución / garantía' },
    { clase: 'fa-solid fa-arrows-rotate', etiqueta: 'Renovación' },
    { clase: 'fa-solid fa-rotate', etiqueta: 'Rotación' },
    { clase: 'fa-solid fa-recycle', etiqueta: 'Reciclaje / reutilizable' },
    { clase: 'fa-solid fa-leaf', etiqueta: 'Ecológico' },
    { clase: 'fa-solid fa-seedling', etiqueta: 'Planta / naturaleza' },
    { clase: 'fa-solid fa-clipboard-check', etiqueta: 'Lista verificada' },
    { clase: 'fa-solid fa-calendar-check', etiqueta: 'Fecha confirmada' },
    { clase: 'fa-solid fa-stopwatch', etiqueta: 'Cronómetro / entrega' },
    { clase: 'fa-solid fa-clock', etiqueta: 'Reloj / horario' },
    { clase: 'fa-solid fa-gauge-high', etiqueta: 'Velocidad' },
    { clase: 'fa-solid fa-bolt', etiqueta: 'Rayo / rápido' },

    // ---- Soporte y contacto ----
    { clase: 'fa-solid fa-headset', etiqueta: 'Auriculares / soporte' },
    { clase: 'fa-solid fa-headphones', etiqueta: 'Cascos' },
    { clase: 'fa-solid fa-life-ring', etiqueta: 'Salvavidas / ayuda' },
    { clase: 'fa-solid fa-circle-question', etiqueta: 'Preguntas' },
    { clase: 'fa-solid fa-circle-info', etiqueta: 'Información' },
    { clase: 'fa-solid fa-circle-exclamation', etiqueta: 'Atención' },
    { clase: 'fa-solid fa-bell', etiqueta: 'Campana / avisos' },
    { clase: 'fa-solid fa-envelope', etiqueta: 'Sobre / email' },
    { clase: 'fa-solid fa-phone', etiqueta: 'Teléfono' },
    { clase: 'fa-solid fa-phone-flip', etiqueta: 'Celular' },
    { clase: 'fa-solid fa-message', etiqueta: 'Mensaje' },
    { clase: 'fa-solid fa-comment', etiqueta: 'Burbuja de mensaje' },
    { clase: 'fa-solid fa-comments', etiqueta: 'Comentarios' },
    { clase: 'fa-solid fa-comment-dots', etiqueta: 'Comentario' },
    { clase: 'fa-solid fa-id-card', etiqueta: 'Carnet' },
    { clase: 'fa-solid fa-user', etiqueta: 'Usuario' },
    { clase: 'fa-solid fa-users', etiqueta: 'Usuarios / comunidad' },
    { clase: 'fa-solid fa-users-gear', etiqueta: 'Usuarios y ajustes' },
    { clase: 'fa-solid fa-hand-holding-heart', etiqueta: 'Cuidado al cliente' },
    { clase: 'fa-solid fa-heart-pulse', etiqueta: 'Pulso / salud' },

    // ---- Tienda y compras ----
    { clase: 'fa-solid fa-store', etiqueta: 'Tienda' },
    { clase: 'fa-solid fa-shop', etiqueta: 'Comercio' },
    { clase: 'fa-solid fa-cart-shopping', etiqueta: 'Carrito' },
    { clase: 'fa-solid fa-cart-plus', etiqueta: 'Agregar al carrito' },
    { clase: 'fa-solid fa-cart-flatbed', etiqueta: 'Carrito de carga' },
    { clase: 'fa-solid fa-bag-shopping', etiqueta: 'Bolsa de compras' },
    { clase: 'fa-solid fa-basket-shopping', etiqueta: 'Canasto' },
    { clase: 'fa-solid fa-gift', etiqueta: 'Regalo' },
    { clase: 'fa-solid fa-gifts', etiqueta: 'Regalos' },
    { clase: 'fa-solid fa-cake-candles', etiqueta: 'Torta / cumple' },
    { clase: 'fa-solid fa-champagne-glasses', etiqueta: 'Festejo' },
    { clase: 'fa-solid fa-magnifying-glass', etiqueta: 'Buscar' },
    { clase: 'fa-solid fa-list-check', etiqueta: 'Lista de control' },
    { clase: 'fa-solid fa-list', etiqueta: 'Lista' },
    { clase: 'fa-solid fa-clipboard-list', etiqueta: 'Planilla' },
    { clase: 'fa-solid fa-file-lines', etiqueta: 'Documento' },
    { clase: 'fa-solid fa-file-circle-check', etiqueta: 'Documento verificado' },
    { clase: 'fa-solid fa-folder', etiqueta: 'Carpeta' },
    { clase: 'fa-solid fa-folder-open', etiqueta: 'Carpeta abierta' },
    { clase: 'fa-solid fa-file-export', etiqueta: 'Exportar' },
    { clase: 'fa-solid fa-download', etiqueta: 'Descargar' },
    { clase: 'fa-solid fa-print', etiqueta: 'Imprimir' },
    { clase: 'fa-solid fa-share-nodes', etiqueta: 'Compartir' },
    { clase: 'fa-solid fa-link', etiqueta: 'Enlace' },
    { clase: 'fa-solid fa-bookmark', etiqueta: 'Marcador' },
    { clase: 'fa-solid fa-heart-circle-check', etiqueta: 'Confiable' },
    { clase: 'fa-solid fa-flag', etiqueta: 'Bandera' },

    // ---- Tecnología y soporte técnico ----
    { clase: 'fa-solid fa-wifi', etiqueta: 'WiFi / online' },
    { clase: 'fa-solid fa-signal', etiqueta: 'Señal' },
    { clase: 'fa-solid fa-mobile-screen', etiqueta: 'Celular (pantalla)' },
    { clase: 'fa-solid fa-tablet', etiqueta: 'Tablet' },
    { clase: 'fa-solid fa-laptop', etiqueta: 'Notebook' },
    { clase: 'fa-solid fa-computer', etiqueta: 'Computadora' },
    { clase: 'fa-solid fa-display', etiqueta: 'Monitor' },
    { clase: 'fa-solid fa-camera', etiqueta: 'Cámara' },
    { clase: 'fa-solid fa-video', etiqueta: 'Video' },
    { clase: 'fa-solid fa-images', etiqueta: 'Imágenes' },
    { clase: 'fa-solid fa-image', etiqueta: 'Imagen' },
    { clase: 'fa-solid fa-gear', etiqueta: 'Ajustes' },
    { clase: 'fa-solid fa-sliders', etiqueta: 'Configuración' },
    { clase: 'fa-solid fa-wrench', etiqueta: 'Llave inglesa' },
    { clase: 'fa-solid fa-screwdriver-wrench', etiqueta: 'Herramientas' },
    { clase: 'fa-solid fa-toolbox', etiqueta: 'Caja de herramientas' },
    { clase: 'fa-solid fa-plug', etiqueta: 'Enchufe' },
    { clase: 'fa-solid fa-battery-full', etiqueta: 'Batería llena' },
    { clase: 'fa-solid fa-database', etiqueta: 'Base de datos' },
    { clase: 'fa-solid fa-network-wired', etiqueta: 'Red' },
    { clase: 'fa-solid fa-sitemap', etiqueta: 'Mapa del sitio' },

    // ---- Salud y cuidado ----
    { clase: 'fa-solid fa-kit-medical', etiqueta: 'Botiquín' },
    { clase: 'fa-solid fa-first-aid', etiqueta: 'Primeros auxilios' },
    { clase: 'fa-solid fa-truck-medical', etiqueta: 'Ambulancia' },
    { clase: 'fa-solid fa-hospital', etiqueta: 'Hospital' },
    { clase: 'fa-solid fa-bottle-water', etiqueta: 'Agua' },
    { clase: 'fa-solid fa-mug-hot', etiqueta: 'Taza caliente' },
    { clase: 'fa-solid fa-utensils', etiqueta: 'Cubiertos' },

    // ---- Varios / generales ----
    { clase: 'fa-solid fa-fire', etiqueta: 'Popular / destacado' },
    { clase: 'fa-solid fa-wand-magic-sparkles', etiqueta: 'Magia' },
    { clase: 'fa-solid fa-puzzle-piece', etiqueta: 'Rompecabezas' },
    { clase: 'fa-solid fa-lightbulb', etiqueta: 'Idea' },
    { clase: 'fa-solid fa-bullseye', etiqueta: 'Objetivo' },
    { clase: 'fa-solid fa-people-group', etiqueta: 'Grupo' },
    { clase: 'fa-solid fa-face-smile', etiqueta: 'Sonrisa' },
    { clase: 'fa-solid fa-face-grin-stars', etiqueta: 'Emoji estrella' },
    { clase: 'fa-solid fa-infinity', etiqueta: 'Infinito' },
    { clase: 'fa-solid fa-code', etiqueta: 'Código' },
    { clase: 'fa-solid fa-terminal', etiqueta: 'Terminal' },
    { clase: 'fa-solid fa-rocket', etiqueta: 'Cohete' },
    { clase: 'fa-solid fa-arrow-trend-up', etiqueta: 'Tendencia / creciendo' },
    { clase: 'fa-solid fa-chart-line', etiqueta: 'Gráfico de línea' },
    { clase: 'fa-solid fa-chart-column', etiqueta: 'Gráfico de barras' },
    { clase: 'fa-solid fa-chart-pie', etiqueta: 'Gráfico de torta' },
    { clase: 'fa-solid fa-paper-plane', etiqueta: 'Enviar' },
    { clase: 'fa-solid fa-hand', etiqueta: 'Mano' },
    { clase: 'fa-solid fa-hands', etiqueta: 'Manos' },
    { clase: 'fa-solid fa-hand-holding', etiqueta: 'Sosteniendo' },

    // ---- Redes sociales (fa-brands) ----
    { clase: 'fa-brands fa-whatsapp', etiqueta: 'WhatsApp' },
    { clase: 'fa-brands fa-instagram', etiqueta: 'Instagram' },
    { clase: 'fa-brands fa-facebook-f', etiqueta: 'Facebook' },
    { clase: 'fa-brands fa-facebook', etiqueta: 'Facebook (cuadro)' },
    { clase: 'fa-brands fa-tiktok', etiqueta: 'TikTok' },
    { clase: 'fa-brands fa-youtube', etiqueta: 'YouTube' },
    { clase: 'fa-brands fa-x-twitter', etiqueta: 'X (Twitter)' },
    { clase: 'fa-brands fa-pinterest', etiqueta: 'Pinterest' },
    { clase: 'fa-brands fa-linkedin-in', etiqueta: 'LinkedIn' },
    { clase: 'fa-brands fa-telegram', etiqueta: 'Telegram' },
    { clase: 'fa-brands fa-snapchat', etiqueta: 'Snapchat' }
];