// iconos-tabler.js — Catálogo curado de íconos Tabler para la
// sección Iconos del dashboard (iconos-pie).
//
// Cada entrada: { clase, etiqueta }. La etiqueta (y la clase) se usan para
// el buscador del selector. Solo se listan nombres que existen en Tabler
// 3.48.0, cubriendo los usos típicos de una tienda:
// pagos, envíos, garantías, soporte, contacto y redes.
//
// La clase va sin prefijo de familia: Tabler no distingue solid de regular, y
// los brand tienen nombre propio (ti-brand-*). Varios íconos de FA que eran
// distintos colapsaron al mismo equivalente (fa-cc-amex y fa-credit-card, por
// ejemplo), así que sus etiquetas quedaron unidas en una sola entrada: el
// buscador sigue encontrándolos por cualquiera de los dos nombres.
//
// Si agregás un ícono que no esté en el subconjunto de la fuente, corré
// `npm run build:iconos` para regenerar assets/tabler/.

export const ICONOS_TABLER = [
    // ---- Pagos y dinero ----
    { clase: 'ti ti-credit-card', etiqueta: 'Tarjeta de crédito / American Express' },
    { clase: 'ti ti-building-bank', etiqueta: 'Banco' },
    { clase: 'ti ti-wallet', etiqueta: 'Billetera' },
    { clase: 'ti ti-currency-dollar', etiqueta: 'Dinero / billetes / Transferencia / Peso / moneda' },
    { clase: 'ti ti-cash-register', etiqueta: 'Caja registradora' },
    { clase: 'ti ti-receipt', etiqueta: 'Ticket / recibo' },
    { clase: 'ti ti-barcode', etiqueta: 'Código de barras' },
    { clase: 'ti ti-qrcode', etiqueta: 'Código QR' },
    { clase: 'ti ti-tag', etiqueta: 'Etiqueta' },
    { clase: 'ti ti-tags', etiqueta: 'Etiquetas / precios' },
    { clase: 'ti ti-percentage', etiqueta: 'Descuento / porcentaje' },
    { clase: 'ti ti-cash', etiqueta: 'Pago en mano / Bolsas de dinero' },
    { clase: 'ti ti-friends', etiqueta: 'Acuerdo / confianza' },
    { clase: 'ti ti-pig-money', etiqueta: 'Ahorro' },
    { clase: 'ti ti-coins', etiqueta: 'Monedas' },

    // ---- Marcas de pago ----
    { clase: 'ti ti-brand-visa', etiqueta: 'Visa' },
    { clase: 'ti ti-brand-mastercard', etiqueta: 'Mastercard' },
    { clase: 'ti ti-brand-paypal', etiqueta: 'PayPal (tarjeta)' },
    { clase: 'ti ti-brand-google', etiqueta: 'Google Pay' },
    { clase: 'ti ti-brand-apple', etiqueta: 'Apple Pay' },
    { clase: 'ti ti-currency-bitcoin', etiqueta: 'Bitcoin' },

    // ---- Envíos y logística ----
    { clase: 'ti ti-truck', etiqueta: 'Camión / envío / Envío rápido' },
    { clase: 'ti ti-truck-loading', etiqueta: 'Descarga / carga / Mudanza' },
    { clase: 'ti ti-truck-delivery', etiqueta: 'Envío en camino' },
    { clase: 'ti ti-caravan', etiqueta: 'Furgoneta' },
    { clase: 'ti ti-box', etiqueta: 'Caja / paquete' },
    { clase: 'ti ti-packages', etiqueta: 'Paquetes apilados' },
    { clase: 'ti ti-package', etiqueta: 'Caja abierta' },
    { clase: 'ti ti-archive', etiqueta: 'Paquete archivado' },
    { clase: 'ti ti-cube', etiqueta: 'Cubo' },
    { clase: 'ti ti-building-warehouse', etiqueta: 'Depósito' },
    { clase: 'ti ti-plane', etiqueta: 'Avión' },
    { clase: 'ti ti-plane-departure', etiqueta: 'Avión despegue' },
    { clase: 'ti ti-plane-arrival', etiqueta: 'Avión llegada' },
    { clase: 'ti ti-ship', etiqueta: 'Barco' },
    { clase: 'ti ti-car', etiqueta: 'Auto' },
    { clase: 'ti ti-car-4wd', etiqueta: 'Auto de lado' },
    { clase: 'ti ti-motorbike', etiqueta: 'Moto' },
    { clase: 'ti ti-bike', etiqueta: 'Bicicleta' },
    { clase: 'ti ti-bus', etiqueta: 'Colectivo' },
    { clase: 'ti ti-train', etiqueta: 'Subte' },
    { clase: 'ti ti-briefcase', etiqueta: 'Valija' },
    { clase: 'ti ti-map-pin', etiqueta: 'Ubicación / Pin de mapa' },
    { clase: 'ti ti-map', etiqueta: 'Mapa' },
    { clase: 'ti ti-route', etiqueta: 'Ruta / recorrido' },
    { clase: 'ti ti-compass', etiqueta: 'Brújula' },
    { clase: 'ti ti-world', etiqueta: 'Globo / todo el país' },

    // ---- Garantías y seguridad ----
    { clase: 'ti ti-shield', etiqueta: 'Escudo' },
    { clase: 'ti ti-shield-half', etiqueta: 'Escudo de seguridad' },
    { clase: 'ti ti-shield-heart', etiqueta: 'Protección' },
    { clase: 'ti ti-shield-check', etiqueta: 'Escudo con protección' },
    { clase: 'ti ti-lock', etiqueta: 'Candado / seguro' },
    { clase: 'ti ti-lock-open', etiqueta: 'Candado abierto' },
    { clase: 'ti ti-key', etiqueta: 'Llave' },
    { clase: 'ti ti-fingerprint', etiqueta: 'Huella digital' },
    { clase: 'ti ti-user-shield', etiqueta: 'Usuario protegido' },
    { clase: 'ti ti-user-check', etiqueta: 'Usuario verificado' },
    { clase: 'ti ti-lock-access', etiqueta: 'Cuenta con candado' },
    { clase: 'ti ti-checkbox', etiqueta: 'Verificación aprobada / Casilla aprobada' },
    { clase: 'ti ti-circle-check', etiqueta: 'Círculo aprobado' },
    { clase: 'ti ti-check', etiqueta: 'Check' },
    { clase: 'ti ti-checks', etiqueta: 'Doble check' },
    { clase: 'ti ti-certificate', etiqueta: 'Certificado' },
    { clase: 'ti ti-award', etiqueta: 'Premio / garantía' },
    { clase: 'ti ti-medal', etiqueta: 'Medalla' },
    { clase: 'ti ti-trophy', etiqueta: 'Trofeo' },
    { clase: 'ti ti-crown', etiqueta: 'Corona / categoría' },
    { clase: 'ti ti-diamond', etiqueta: 'Gema / calidad' },
    { clase: 'ti ti-star', etiqueta: 'Estrella' },
    { clase: 'ti ti-heart', etiqueta: 'Corazón' },
    { clase: 'ti ti-thumb-up', etiqueta: 'Me gusta' },

    // ---- Garantía y devoluciones ----
    { clase: 'ti ti-arrow-back-up', etiqueta: 'Devolución / garantía' },
    { clase: 'ti ti-refresh', etiqueta: 'Renovación' },
    { clase: 'ti ti-rotate', etiqueta: 'Rotación' },
    { clase: 'ti ti-recycle', etiqueta: 'Reciclaje / reutilizable' },
    { clase: 'ti ti-leaf', etiqueta: 'Ecológico' },
    { clase: 'ti ti-seedling', etiqueta: 'Planta / naturaleza' },
    { clase: 'ti ti-clipboard-check', etiqueta: 'Lista verificada' },
    { clase: 'ti ti-calendar-check', etiqueta: 'Fecha confirmada' },
    { clase: 'ti ti-stopwatch', etiqueta: 'Cronómetro / entrega' },
    { clase: 'ti ti-clock', etiqueta: 'Reloj / horario' },
    { clase: 'ti ti-gauge', etiqueta: 'Velocidad' },
    { clase: 'ti ti-bolt', etiqueta: 'Rayo / rápido' },

    // ---- Soporte y contacto ----
    { clase: 'ti ti-headset', etiqueta: 'Auriculares / soporte' },
    { clase: 'ti ti-headphones', etiqueta: 'Cascos' },
    { clase: 'ti ti-lifebuoy', etiqueta: 'Salvavidas / ayuda' },
    { clase: 'ti ti-help-circle', etiqueta: 'Preguntas' },
    { clase: 'ti ti-info-circle', etiqueta: 'Información' },
    { clase: 'ti ti-alert-circle', etiqueta: 'Atención' },
    { clase: 'ti ti-bell', etiqueta: 'Campana / avisos' },
    { clase: 'ti ti-mail', etiqueta: 'Sobre / email' },
    { clase: 'ti ti-phone', etiqueta: 'Teléfono / Celular' },
    { clase: 'ti ti-message', etiqueta: 'Burbuja de mensaje' },
    { clase: 'ti ti-messages', etiqueta: 'Comentarios' },
    { clase: 'ti ti-message-dots', etiqueta: 'Comentario' },
    { clase: 'ti ti-id', etiqueta: 'Carnet' },
    { clase: 'ti ti-user', etiqueta: 'Usuario' },
    { clase: 'ti ti-users', etiqueta: 'Usuarios / comunidad / Grupo / Manos' },
    { clase: 'ti ti-users-group', etiqueta: 'Usuarios y ajustes' },
    { clase: 'ti ti-heart-handshake', etiqueta: 'Cuidado al cliente' },
    { clase: 'ti ti-heartbeat', etiqueta: 'Pulso / salud' },

    // ---- Tienda y compras ----
    { clase: 'ti ti-building-store', etiqueta: 'Tienda' },
    { clase: 'ti ti-building', etiqueta: 'Comercio' },
    { clase: 'ti ti-shopping-cart', etiqueta: 'Carrito' },
    { clase: 'ti ti-shopping-cart-plus', etiqueta: 'Agregar al carrito' },
    { clase: 'ti ti-trolley', etiqueta: 'Carrito de carga' },
    { clase: 'ti ti-shopping-bag', etiqueta: 'Bolsa de compras' },
    { clase: 'ti ti-basket', etiqueta: 'Canasto' },
    { clase: 'ti ti-gift', etiqueta: 'Regalos' },
    { clase: 'ti ti-cake', etiqueta: 'Torta / cumple' },
    { clase: 'ti ti-glass-cocktail', etiqueta: 'Festejo' },
    { clase: 'ti ti-search', etiqueta: 'Buscar' },
    { clase: 'ti ti-list-check', etiqueta: 'Lista de control' },
    { clase: 'ti ti-list', etiqueta: 'Lista' },
    { clase: 'ti ti-clipboard-list', etiqueta: 'Planilla' },
    { clase: 'ti ti-file-text', etiqueta: 'Documento' },
    { clase: 'ti ti-file-check', etiqueta: 'Documento verificado' },
    { clase: 'ti ti-folder', etiqueta: 'Carpeta' },
    { clase: 'ti ti-folder-open', etiqueta: 'Carpeta abierta' },
    { clase: 'ti ti-file-export', etiqueta: 'Exportar' },
    { clase: 'ti ti-download', etiqueta: 'Descargar' },
    { clase: 'ti ti-printer', etiqueta: 'Imprimir' },
    { clase: 'ti ti-share', etiqueta: 'Compartir' },
    { clase: 'ti ti-link', etiqueta: 'Enlace' },
    { clase: 'ti ti-bookmark', etiqueta: 'Marcador' },
    { clase: 'ti ti-heart-check', etiqueta: 'Confiable' },
    { clase: 'ti ti-flag', etiqueta: 'Bandera' },

    // ---- Tecnología y soporte técnico ----
    { clase: 'ti ti-wifi', etiqueta: 'WiFi / online' },
    { clase: 'ti ti-antenna', etiqueta: 'Señal' },
    { clase: 'ti ti-device-mobile', etiqueta: 'Celular (pantalla)' },
    { clase: 'ti ti-device-tablet', etiqueta: 'Tablet' },
    { clase: 'ti ti-device-laptop', etiqueta: 'Notebook' },
    { clase: 'ti ti-device-desktop', etiqueta: 'Computadora / Monitor' },
    { clase: 'ti ti-camera', etiqueta: 'Cámara' },
    { clase: 'ti ti-video', etiqueta: 'Video' },
    { clase: 'ti ti-photo-plus', etiqueta: 'Imágenes' },
    { clase: 'ti ti-photo', etiqueta: 'Imagen' },
    { clase: 'ti ti-settings', etiqueta: 'Ajustes' },
    { clase: 'ti ti-adjustments', etiqueta: 'Configuración' },
    { clase: 'ti ti-tool', etiqueta: 'Llave inglesa' },
    { clase: 'ti ti-tools', etiqueta: 'Herramientas' },
    { clase: 'ti ti-hammer', etiqueta: 'Caja de herramientas' },
    { clase: 'ti ti-plug', etiqueta: 'Enchufe' },
    { clase: 'ti ti-battery-4', etiqueta: 'Batería llena' },
    { clase: 'ti ti-database', etiqueta: 'Base de datos' },
    { clase: 'ti ti-network', etiqueta: 'Red' },
    { clase: 'ti ti-sitemap', etiqueta: 'Mapa del sitio' },

    // ---- Salud y cuidado ----
    { clase: 'ti ti-first-aid-kit', etiqueta: 'Botiquín / Primeros auxilios' },
    { clase: 'ti ti-ambulance', etiqueta: 'Ambulancia' },
    { clase: 'ti ti-hospital', etiqueta: 'Hospital' },
    { clase: 'ti ti-bottle', etiqueta: 'Agua' },
    { clase: 'ti ti-coffee', etiqueta: 'Taza caliente' },
    { clase: 'ti ti-tools-kitchen-2', etiqueta: 'Cubiertos' },

    // ---- Varios / generales ----
    { clase: 'ti ti-flame', etiqueta: 'Popular / destacado' },
    { clase: 'ti ti-wand', etiqueta: 'Magia' },
    { clase: 'ti ti-puzzle', etiqueta: 'Rompecabezas' },
    { clase: 'ti ti-bulb', etiqueta: 'Idea' },
    { clase: 'ti ti-target', etiqueta: 'Objetivo' },
    { clase: 'ti ti-mood-smile', etiqueta: 'Sonrisa / Emoji estrella' },
    { clase: 'ti ti-infinity', etiqueta: 'Infinito' },
    { clase: 'ti ti-code', etiqueta: 'Código' },
    { clase: 'ti ti-terminal', etiqueta: 'Terminal' },
    { clase: 'ti ti-rocket', etiqueta: 'Cohete' },
    { clase: 'ti ti-trending-up', etiqueta: 'Tendencia / creciendo' },
    { clase: 'ti ti-chart-line', etiqueta: 'Gráfico de línea' },
    { clase: 'ti ti-chart-bar', etiqueta: 'Gráfico de barras' },
    { clase: 'ti ti-chart-pie', etiqueta: 'Gráfico de torta' },
    { clase: 'ti ti-send', etiqueta: 'Enviar' },
    { clase: 'ti ti-hand-finger', etiqueta: 'Mano' },
    { clase: 'ti ti-hand-stop', etiqueta: 'Sosteniendo' },

    // ---- Redes sociales ----
    { clase: 'ti ti-brand-whatsapp', etiqueta: 'WhatsApp' },
    { clase: 'ti ti-brand-instagram', etiqueta: 'Instagram' },
    { clase: 'ti ti-brand-facebook', etiqueta: 'Facebook (cuadro)' },
    { clase: 'ti ti-brand-tiktok', etiqueta: 'TikTok' },
    { clase: 'ti ti-brand-youtube', etiqueta: 'YouTube' },
    { clase: 'ti ti-brand-x', etiqueta: 'X (Twitter)' },
    { clase: 'ti ti-brand-pinterest', etiqueta: 'Pinterest' },
    { clase: 'ti ti-brand-linkedin', etiqueta: 'LinkedIn' },
    { clase: 'ti ti-brand-telegram', etiqueta: 'Telegram' },
    { clase: 'ti ti-brand-snapchat', etiqueta: 'Snapchat' },
];